---
apiVersion: v1
kind: Service
metadata:
  name: blockscout
  namespace: blockscout
  labels:
    app: blockscout
spec:
  selector:
    app: blockscout
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
  namespace: blockscout
  labels:
    app: blockscout
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blockscout
  template:
    metadata:
      labels:
        app: blockscout
    spec:
      containers:
      - name: blockscout
        image: 434305222479.dkr.ecr.ap-southeast-1.amazonaws.com/prime-explorer:latest
        ports:
          - containerPort: 4000
        command: [/bin/sh]
        args: ["-c", "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"]
        env:
          - name: DATABASE_URL
            value: postgresql://admin:blockscout@blockscout-postgres:5432/blockscout?ssl=false
        envFrom:
          - configMapRef:
              name: blockscout
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"