apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - blockscout.yaml
  - blockscout-postgres.yaml
  - loadbalancer.yaml
configMapGenerator:
  - name: blockscout-postgres
    namespace: blockscout
    envs:
      - postgres.env
  - name: blockscout
    namespace: blockscout
    envs:
      - blockscout.env