apiVersion: v1
kind: Service
metadata:
  name: blockscout-service-lb
  namespace: blockscout
spec:
  type: LoadBalancer
  selector:
    app: blockscout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000